spring:
  datasource:
    url:  jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&repareThreshold=0
    username: postgres.eubanztqqqhczzowrkvz
    password: vP8TDb8IsAx6ajL7
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.my.todo.dto
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
